apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "cm9vdA=="
  MYSQL_DATABASE: "YXBwX2Ri"
  MYSQL_USER: "bXlzcWx1c2Vy"
  MYSQL_PASSWORD: "cm9vdA=="
